// Quirkly Extension Configuration - DYNAMIC RUNTIME CONFIG
// This file is dynamically generated by build scripts based on extension.env
// Generated on 2025-10-16T18:07:17.937Z for DEVELOPMENT environment

const QuirklyConfig = {
  // Environment variables - injected at build time
  _envVars: {
    EXT_ENV: 'development',
    DEV_BASE_URL: 'http://localhost:3000',
    DEV_DASHBOARD_URL: 'http://localhost:3000',
    PROD_BASE_URL: 'https://quirkly.technioz.com',
    PROD_DASHBOARD_URL: 'https://quirkly.technioz.com',
    AUTH_ENDPOINT: '/api/auth/validate',
    REPLY_ENDPOINT: '/api/reply/generate',
    PROFILE_ENDPOINT: '/api/profile/extract'
  },

  // Environment detection - truly dynamic based on injected vars
  isDevelopment: function() {
    return this._envVars.EXT_ENV === 'development';
  },

  // Get current environment configuration - truly dynamic
  getConfig: function() {
    const isDev = this.isDevelopment();
    
    const config = {
      environment: isDev ? 'development' : 'production',
      baseUrl: isDev ? this._envVars.DEV_BASE_URL : this._envVars.PROD_BASE_URL,
      dashboardUrl: isDev ? this._envVars.DEV_DASHBOARD_URL : this._envVars.PROD_DASHBOARD_URL,
      authEndpoint: this._envVars.AUTH_ENDPOINT,
      replyEndpoint: this._envVars.REPLY_ENDPOINT,
      profileEndpoint: this._envVars.PROFILE_ENDPOINT,
      isDev: isDev
    };

    // Build full URLs
    config.authUrl = config.baseUrl + config.authEndpoint;
    config.replyUrl = config.baseUrl + config.replyEndpoint;
    config.profileUrl = config.baseUrl + config.profileEndpoint;

    return config;
  },

  // Get specific URLs - truly dynamic
  getAuthUrl: function() {
    return this.getConfig().authUrl;
  },

  getReplyUrl: function() {
    return this.getConfig().replyUrl;
  },

  getDashboardUrl: function() {
    return this.getConfig().dashboardUrl;
  },

  getProfileUrl: function() {
    return this.getConfig().profileUrl;
  },

  // Debug info
  getEnvironmentInfo: function() {
    const config = this.getConfig();
    
    console.log('Quirkly Environment Info (DYNAMIC):', {
      environment: config.environment,
      authUrl: config.authUrl,
      replyUrl: config.replyUrl,
      dashboardUrl: config.dashboardUrl,
      extEnv: this._envVars.EXT_ENV,
      isDevelopment: this.isDevelopment(),
      buildTime: '2025-10-16T18:07:17.937Z'
    });
    return config;
  }
};

// Make it available globally
if (typeof window !== 'undefined') {
  window.QuirklyConfig = QuirklyConfig;
}

// Export for modules (if needed)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = QuirklyConfig;
}